import { createFileRoute } from "@tanstack/react-router";
import { CalendarRange } from "lucide-react";
import { useState } from "react";
import { AiOutputCard } from "@/components/AiOutputCard";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAiTool } from "@/lib/use-ai-tool";

export const Route = createFileRoute("/planner")({
  head: () => ({
    meta: [
      { title: "AI Task Planner | Workplace AI" },
      {
        name: "description",
        content:
          "Generate prioritised daily or weekly time-blocked schedules from your task list with high, medium and low priorities.",
      },
      { property: "og:title", content: "AI Task Planner" },
      {
        property: "og:description",
        content: "Prioritised, time-blocked daily and weekly schedules generated by AI.",
      },
    ],
  }),
  component: PlannerPage,
});

const RANGES = ["Daily", "Weekly"] as const;
const PRIORITIES = [
  { label: "High Priority", hint: "Deep work, deadlines", tone: "text-destructive" },
  { label: "Medium Priority", hint: "Collaboration, reviews", tone: "text-warning" },
  { label: "Low Priority", hint: "Admin, batching", tone: "text-success" },
];

function PlannerPage() {
  const [range, setRange] = useState<(typeof RANGES)[number]>("Daily");
  const [hours, setHours] = useState("09:00 - 17:00");
  const [tasks, setTasks] = useState("");
  const { output, setOutput, loading, run } = useAiTool("planner");

  const submit = () =>
    run(
      `Schedule type: ${range}\nWorking hours: ${hours}\nTasks with any known priority or deadline:\n${tasks}\n\nProduce the time-blocked plan.`,
    );

  return (
    <AppShell
      title="AI Task Planner"
      subtitle="Turn a task list into a realistic, prioritised time-blocked schedule."
    >
      <div className="grid gap-6 lg:grid-cols-[minmax(0,380px)_1fr]">
        <section className="surface-card space-y-4 p-5">
          <div className="space-y-2">
            <Label>Schedule type</Label>
            <div className="grid grid-cols-2 gap-2">
              {RANGES.map((r) => (
                <button
                  key={r}
                  type="button"
                  onClick={() => setRange(r)}
                  className={
                    r === range
                      ? "rounded-xl gradient-primary px-3 py-2 text-xs font-semibold text-primary-foreground"
                      : "rounded-xl border border-border bg-card px-3 py-2 text-xs font-medium text-muted-foreground transition-smooth hover:border-primary hover:text-foreground"
                  }
                >
                  {r}
                </button>
              ))}
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="hours">Working hours</Label>
            <Input id="hours" value={hours} onChange={(e) => setHours(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="tasks">Tasks</Label>
            <Textarea
              id="tasks"
              rows={8}
              placeholder={"Finish Q3 report (high, due Thu)\nTeam stand-up 09:15\nInbox triage"}
              value={tasks}
              onChange={(e) => setTasks(e.target.value)}
            />
          </div>
          <Button className="w-full" onClick={submit} disabled={loading}>
            <CalendarRange className="mr-2 size-4" />
            {loading ? "Planning..." : `Generate ${range.toLowerCase()} plan`}
          </Button>

          <div className="space-y-2 rounded-xl border border-border p-3">
            {PRIORITIES.map((p) => (
              <div key={p.label} className="flex items-center justify-between text-xs">
                <span className={`font-semibold ${p.tone}`}>{p.label}</span>
                <span className="text-muted-foreground">{p.hint}</span>
              </div>
            ))}
          </div>
        </section>

        <AiOutputCard
          title="Time-blocked schedule"
          value={output}
          onChange={setOutput}
          onRegenerate={submit}
          loading={loading}
          emptyHint="List your tasks and working hours, then generate a prioritised, time-blocked plan."
        />
      </div>
    </AppShell>
  );
}
